### ISSUE TITLE
Question about Priority

### ISSUE THREAD

**Issue by DHOFM** [Azure/BatchAI#2]
Hi,
is it possible to use low priority with Batch AI ? How can this be done according to your scripts ? What would happen if a batch job is deleted because of it´s low priority, e.g. would the model be lost, if training is not completed ?

Thanks.

Kind regards,
Dirk

**Comment by lliimsft** [comment]
Hi Dirk,

Yes, you can use low-priority node with Batch AI. In python, please specify vm_priority='lowpriority' in your ClusterCreateParameters object. 

If the node is deleted because of low-priority, all local job data on the node will be lost. we recommend to use shared volume such as Azure File Share and training checkpoint if you submit a long-run training job.

**Comment by Vamanbedekar** [comment]
Yes, you can use low priority with Batch AI (see https://docs.microsoft.com/en-us/rest/api/batchai/Clusters/Create#definitions_virtualmachineconfiguration) . Because you will be keeping your model in a FileShare (azure file share, or NFS or your own Distributed File System) and mount that on the cluster node, the model will not be lost. Similarly for any intermediate models that you might have check pointed.

**Comment by lliimsft** [comment]
close the issue as it is not active
